//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kundenportal.AdminUi.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kundenportal.AdminUi.WebApp.Resources.Texts.en", typeof(Texts_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string ButtonTextCreate {
            get {
                return ResourceManager.GetString("ButtonTextCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again..
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelEditStructureGroupName {
            get {
                return ResourceManager.GetString("LabelEditStructureGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No structure groups found..
        /// </summary>
        internal static string NoStructureGroups {
            get {
                return ResourceManager.GetString("NoStructureGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A structure is a folder for which users can receive permissons and for which predefined folder and file structures can be created..
        /// </summary>
        internal static string StructureExplanation {
            get {
                return ResourceManager.GetString("StructureExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A structure group is a grouping of structures for which structure group which belong together can be created together. An example is multiple structures for the same project..
        /// </summary>
        internal static string StructureGroupExplanation {
            get {
                return ResourceManager.GetString("StructureGroupExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create structure.
        /// </summary>
        internal static string TitleCreateStructure {
            get {
                return ResourceManager.GetString("TitleCreateStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create structure group.
        /// </summary>
        internal static string TitleCreateStructureGroup {
            get {
                return ResourceManager.GetString("TitleCreateStructureGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit structure group.
        /// </summary>
        internal static string TitleEditStructureGroup {
            get {
                return ResourceManager.GetString("TitleEditStructureGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending structure groups.
        /// </summary>
        internal static string TitlePendingStructureGroups {
            get {
                return ResourceManager.GetString("TitlePendingStructureGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure groups.
        /// </summary>
        internal static string TitleStructureGroups {
            get {
                return ResourceManager.GetString("TitleStructureGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options for structure groups {0}.
        /// </summary>
        internal static string TitleTextStructureGroupOptions {
            get {
                return ResourceManager.GetString("TitleTextStructureGroupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path part contains invalid characters, invalid characters are: &lt; &gt; ? &quot; : | / \ * . ’ # %.
        /// </summary>
        internal static string ValidationErrorEditStructureGroupNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("ValidationErrorEditStructureGroupNameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be provided..
        /// </summary>
        internal static string ValidationErrorFieldRequired {
            get {
                return ResourceManager.GetString("ValidationErrorFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} can be a maximum of {0} characters long..
        /// </summary>
        internal static string ValidationErrorFieldTooLong {
            get {
                return ResourceManager.GetString("ValidationErrorFieldTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A structure group with that name already exists..
        /// </summary>
        internal static string ValidationErrorStructureGroupExists {
            get {
                return ResourceManager.GetString("ValidationErrorStructureGroupExists", resourceCulture);
            }
        }
    }
}
