volumes:
  kundenportal_adminui-dev-db-data:
    
services: 
  db:
    image: postgres:16-alpine
    container_name: kundenportal_adminui-dev-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kundenportal_adminui
      POSTGRES_PASSWORD: Development1+
    volumes:
      - kundenportal_adminui-dev-db-data:/var/lib/postgresql/data
