FROM docker.io/nextcloud:production

# Prevent default files for ALL users (including the initial admin)
RUN rm -rf /usr/src/nextcloud/core/skeleton
# Disable annoying default apps
COPY ./disable-apps.sh /docker-entrypoint-hooks.d/post-installation
# Ensure proper line endings
RUN apt update && apt install dos2unix -y
RUN dos2unix /docker-entrypoint-hooks.d/**/*
